"""empty message

Revision ID: 111164d4ee0f
Revises: 652f2ac17b29
Create Date: 2018-05-15 21:45:34.734309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111164d4ee0f'
down_revision = '652f2ac17b29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###
