"""empty message

Revision ID: 56b219ea79d1
Revises: 
Create Date: 2018-05-31 13:13:34.937769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56b219ea79d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input_controls',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assets',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('asset_category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_category_id'], ['asset_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attributes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('input_control_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('asset_category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_category_id'], ['asset_categories.id'], ),
    sa.ForeignKeyConstraint(['input_control_id'], ['input_controls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute_values',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('attribute_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('attribute_value_str', sa.String(length=36), nullable=True),
    sa.Column('attribute_value_flt', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attribute_values')
    op.drop_table('attributes')
    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('input_controls')
    op.drop_table('asset_categories')
    # ### end Alembic commands ###
