"""empty message

Revision ID: 771adeed3cc8
Revises: 936c7b058373
Create Date: 2018-06-05 20:57:52.617296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '771adeed3cc8'
down_revision = '936c7b058373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'created_at')
    op.drop_column('asset', 'deleted_by')
    op.drop_column('asset', 'deleted_at')
    op.drop_column('asset', 'created_by')
    op.drop_column('asset', 'updated_at')
    op.drop_column('asset', 'updated_by')
    op.drop_column('asset_category', 'created_at')
    op.drop_column('asset_category', 'deleted_by')
    op.drop_column('asset_category', 'deleted_at')
    op.drop_column('asset_category', 'created_by')
    op.drop_column('asset_category', 'updated_at')
    op.drop_column('asset_category', 'updated_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_category', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asset_category', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('asset_category', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asset_category', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('asset_category', sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asset_category', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('updated_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('created_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('deleted_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('asset', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
