"""empty message

Revision ID: 94ce79cfbc36
Revises: 111164d4ee0f
Create Date: 2018-06-01 00:34:37.428329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ce79cfbc36'
down_revision = '111164d4ee0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.Column('serial', sa.String(length=60), nullable=False),
    sa.Column('asset_category_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_category_id'], ['asset_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attribute',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('input_control', sa.String(length=60), nullable=False),
    sa.Column('choices', sa.String(length=250), nullable=False),
    sa.Column('asset_category_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_category_id'], ['asset_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted')
    op.drop_table('attribute')
    op.drop_table('asset')
    op.drop_table('asset_categories')
    # ### end Alembic commands ###
